### PR TITLE
Move binaries into bin folder

### PR DESCRIPTION
**Pull request by janden**
This cleans up the root a little by putting all the compiled binaries (mostly tests) into `bin`. I also modified the Python benchmark scripts to use the new path.

### CODE REVIEW

**Comment by MelodyShih** [comment]
Should we create a `bin` folder for the user?

**Comment by janden** [comment]
> Should we create a `bin` folder for the user?

Yes of course. Forgot about that. Will put it in the Makefile.

**Comment by janden** [comment]
Great. Will merge.

**Comment by janden** [comment]
Although let's wait until #4 is merged. It's easier to deal with conflicts in this PR.

**Pull request merged**
