### PR TITLE
More general .gitignore

### PR DESCRIPTION
**Pull request by tianrluo**
Dear authors,

I made some minor changes to make `.gitignore` more general, and include a way to keep the setting of `LD_LIBRARY_PATH` local to a certain `conda` environment.

Hopefully this can be helpful.

Thanks!

### CODE REVIEW

**Comment by tianrluo** [comment]
`cupy` is needed in the CI testing environment to assess the PR.
Right now the auto test is failing

**Comment by janden** [comment]
Thank you for these contributions @tianrluo. Since this PR incorporates several unrelated changes, it is hard to review as is. I therefore suggest you split it into smaller, logically consistent PRs that we can review one at a time. Furthermore, it is good practice to anchor non-trivial changes (such as adding cupy support) through discussion in an Issue to ensure that there is agreement on the proposed change before proceeding to making such changes to the code.

**Comment by tianrluo** [comment]
@janden
Got it, should I create an issue about adding `cupy` support...?

I will roll back the commit that adds `cupy` support for the moment.

**Comment by janden** [comment]
Again, please split this commit into smaller ones. We cannot review all these changes wholesale. From what I can see, there are a few distinct changes proposed here:
- Changing the `.gitignore`
- Fixes to the README
- Changes to `setup.py`

Please separate these into different PRs with explanations and motivations for each.

**Comment by tianrluo** [comment]
@janden 

Thanks for the suggestion!
I have rolled back the branch.

This commit makes `.gitignore` more automatic in some sense at ignoring unwanted changes.
I felt this was needed when I installed the package by compiling the codes and doing a local pip install.

**Pull request closed without merging**
